apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-auth
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
type: Opaque
stringData:
  githubClientId: {{ .Values.backstage.auth.github.clientId | quote }}
  githubClientSecret: {{ .Values.backstage.auth.github.clientSecret | quote }}
