apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
  namespace: backstage
  labels:
    app: backstage
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-auth
  namespace: backstage
type: Opaque
stringData:
  githubClientId: ""
  githubClientSecret: ""
